---
- id: generate-pipeline
  name: Generate GitLab Pipeline YAML files
  description: Generates GitLab Pipeline YAML files
  entry: generate-pipeline.sh
  language: script
  # We need to take environments.yml here as well, due to how pre-commit works
  # It creates a separate folder to work in and we need environments.yml as a
  # source for the template generation in this temp folder
  files: (environments\.yml|\.gitlab\/ci\/.*\.ya?ml\.j2)$
  # Possible workaround if only environments.yaml changed
  always_run: true
