---
- id: generate-pipeline
  name: Generates GitLab Pipeline YAML files
  description: Generates GitLab Pipeline YAML files
  entry: generate-pipeline.sh
  language: script
  files: \.gitlab\/ci\/.*\.ya?ml\.j2$
